/* automatically generated by rust-bindgen */

#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct webview_priv {
    pub _bindgen_opaque_blob: [u64; 7usize],
}
#[test]
fn bindgen_test_layout_webview_priv() {
    assert_eq!(
        ::std::mem::size_of::<webview_priv>(),
        56usize,
        concat!("Size of: ", stringify!(webview_priv))
    );
    assert_eq!(
        ::std::mem::align_of::<webview_priv>(),
        8usize,
        concat!("Alignment of ", stringify!(webview_priv))
    );
}
